/**
 * This class will be storing the varibles which can be used to controlling the execution of the 
 * Methods
 */
public class HelperVariables {
   
    /**
     * Will be used to control after update method of Event_Trigger
     */
    public static boolean isEventAfterUpdateExecuted = false;
    
    /**
     * This will be used to stop execution of trigger multiple times
     * This is for attandee trigger
     */
     public static Boolean isAttendeeCreateExected = false;
    
}